// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgLKFaSNegxwshEWCr8GAwLMz37vWdqys',
    appId: '1:252050439856:web:5fbe047b5270f3f9b58575',
    messagingSenderId: '252050439856',
    projectId: 'fir-series-27a3d',
    authDomain: 'fir-series-27a3d.firebaseapp.com',
    storageBucket: 'fir-series-27a3d.appspot.com',
    measurementId: 'G-40R1TNXBNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoO0n8rtAzGOodG5fx1lB3IJHg1HM2goY',
    appId: '1:252050439856:android:ed870cf0158cc8ddb58575',
    messagingSenderId: '252050439856',
    projectId: 'fir-series-27a3d',
    storageBucket: 'fir-series-27a3d.appspot.com',
  );
}
